# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import cv2
import test
class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(472, 368)
        self.centralwidget = QtWidgets.QWidget(form)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tipforwater = QtWidgets.QLabel(self.centralwidget)
        self.tipforwater.setGeometry(QtCore.QRect(20, 50, 141, 51))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.tipforwater.setFont(font)
        self.tipforwater.setObjectName("tipforwater")
        self.tipforcariier = QtWidgets.QLabel(self.centralwidget)
        self.tipforcariier.setGeometry(QtCore.QRect(20, 120, 151, 51))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.tipforcariier.setFont(font)
        self.tipforcariier.setObjectName("tipforcariier")
        self.choosewatermark = QtWidgets.QPushButton(self.centralwidget)
        self.choosewatermark.setGeometry(QtCore.QRect(190, 60, 91, 31))
        self.choosewatermark.setObjectName("choosewatermark")
        self.choosecarrier = QtWidgets.QPushButton(self.centralwidget)
        self.choosecarrier.setGeometry(QtCore.QRect(190, 130, 91, 31))
        self.choosecarrier.setObjectName("choosecarrier")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.select = QtWidgets.QPushButton(self.centralwidget)
        self.select.setGeometry(QtCore.QRect(20, 300, 91, 31))
        self.select.setObjectName("select")
        self.impaction = QtWidgets.QPushButton(self.centralwidget)
        self.impaction.setGeometry(QtCore.QRect(320, 130, 91, 31))
        self.impaction.setObjectName("impaction")
        self.paremeter = QtWidgets.QLineEdit(self.centralwidget)
        self.paremeter.setGeometry(QtCore.QRect(20, 260, 113, 21))
        self.paremeter.setObjectName("paremeter")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 131, 21))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(340, 290, 91, 31))
        self.quit.setObjectName("quit")
        self.strength = QtWidgets.QLineEdit(self.centralwidget)
        self.strength.setGeometry(QtCore.QRect(320, 90, 113, 21))
        self.strength.setObjectName("strength")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 50, 131, 21))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        form.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(form)
        self.statusbar.setObjectName("statusbar")
        form.setStatusBar(self.statusbar)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

        self.choosewatermark.clicked.connect(self.getwaterpath)
        self.choosecarrier.clicked.connect(self.getcarrierpath)
        self.impaction.clicked.connect(self.encode)
        self.quit.clicked.connect(self.exit)
        self.select.clicked.connect(self.verdict)
    def exit(self):
        print("See you next time~")
        sys.exit()

    def getwaterpath(self):
        path = QtWidgets.QFileDialog.getOpenFileName()
        if path == ('', ''):
            return 0
        path = str(path[0])
        print(path)
        self.tipforwater.setText(path)

    def getcarrierpath(self):
        path = QtWidgets.QFileDialog.getOpenFileName()
        if path == ('', ''):
            return 0
        path = str(path[0])
        self.tipforcariier.setText(path)

    def encode(self):
        parameter=self.strength.text()
        if parameter=="":
            mes=QMessageBox.question(self,'提示','未输入嵌入强度')
            return 0
        parameter=float(parameter)
        path1 = self.tipforwater.text()
        print(path1)
        path2 = self.tipforcariier.text()
        print(path2)
        watermark = cv2.imread(path1, cv2.IMREAD_GRAYSCALE)
        print("open water")
        carrier = cv2.imread(path2, cv2.IMREAD_GRAYSCALE)
        print("open carrier")
        hide.dct_encode(watermark, carrier,parameter)

    def verdict(self):
        water=cv2.imread("D:/watermark.png",cv2.IMREAD_GRAYSCALE)
        orginal_img=cv2.imread("D:/carrier.png",cv2.IMREAD_GRAYSCALE)
        path = QtWidgets.QFileDialog.getOpenFileName()
        if path == ('', ''):
            return 0
        path = str(path[0])
        img=cv2.imread(path,cv2.IMREAD_GRAYSCALE)
        get_watermark=hide.dct_decode(water,img,orginal_img)
        print("Analyze complete!")
        paramete=self.paremeter.text()
        result=test.getNc(get_watermark,water)
        print("Need",paramete,"result",result)
        if result>=float(paramete):
            test.GetQRCode(img)
            print("this is true")
        else:
            print("it is fake!")
        return 0
    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Anti-Fake System on the Basis of QRcode  --Kevin"))
        self.label.setText(_translate("form", "水印嵌入"))
        self.tipforwater.setText(_translate("form", "水印文件待选择"))
        self.tipforcariier.setText(_translate("form", "载体文件待选择"))
        self.choosewatermark.setText(_translate("form", "选择水印"))
        self.choosecarrier.setText(_translate("form", "选择载体"))
        self.label_4.setText(_translate("form", "防伪鉴别"))
        self.select.setText(_translate("form", "选择图像"))
        self.impaction.setText(_translate("form", "开始嵌入"))
        self.label_5.setText(_translate("form", "严格系数"))
        self.quit.setText(_translate("form", "退出系统"))
        self.label_6.setText(_translate("form", "嵌入强度"))

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow,QMessageBox
import hide
if __name__ == '__main__':
	app = QApplication(sys.argv)
	MainWindow = QMainWindow()
	ui = Ui_form()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())